name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - name: Run database migration
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_TYPE: mysql
        run: npm run migrate
      - name: Run testing
        env:
          HOST: localhost
          PORT: 5001
          DB_HOST_TEST: localhost
          DB_PORT_TEST: 3306
          DB_USER_TEST: root
          DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD }}
          DB_NAME_TEST: ${{ secrets.DB_NAME }}
          DB_TYPE_TEST: mysql
        run: npm test
