name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: qwertymysql
          MYSQL_DATABASE: db_docker
        ports:
          - 3306:3306

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: qwertymysql
          DB_NAME: db_docker
          DB_TYPE: mysql
      - run: npm install
      - name: Run database migration
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: qwertymysql
          DB_NAME: db_docker
          DB_TYPE: mysql
        run: npx sequelize db:migrate
      - run: npm test
